jaeger:
 create: true
 spec:
    strategy: production
    query:
      serviceType: LoadBalancer
      options:
        log-level: debug
        query:
          base-path: /jaeger
    ingress:
      enabled: false
